
project_id = "xzbunrtgbfbhinkzkzhf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.migrate-google-sheets]
verify_jwt = false

[functions.migrate-google-drive-media]
verify_jwt = false

[functions.lexicon-proxy]
verify_jwt = false

[functions.biodiversity-data]
verify_jwt = false
